export const projects = [
  {
    name: "N/A",
    slug: "n-a-1",
    show: "N/A",
    desc: "N/A",
    lang: ["N/A"],
    img: "N/A",
    img2: "N/A",
    img3: "N/A",
    link: "N/A",
    git: "N/A",
  },
  {
    name: "N/A",
    slug: "n-a-2",
    show: "N/A",
    desc: "N/A",
    lang: ["N/A"],
    img: "N/A",
    img2: "N/A",
    img3: "N/A",
    link: "N/A",
    git: "N/A",
  },
  {
    name: "N/A",
    slug: "n-a-3",
    show: "N/A",
    desc: "N/A",
    lang: ["N/A"],
    img: "N/A",
    img2: "N/A",
    img3: "N/A",
    link: "N/A",
    git: "N/A",
  },
  {
    name: "N/A",
    slug: "n-a-4",
    show: "N/A",
    desc: "N/A",
    lang: ["N/A"],
    img: "N/A",
    img2: "N/A",
    img3: "N/A",
    link: "N/A",
    git: "N/A",
  },
  {
    name: "N/A",
    slug: "n-a-5",
    show: "N/A",
    desc: "N/A",
    lang: ["N/A"],
    img: "N/A",
    link: "N/A",
    git: "N/A",
    problem: "N/A",
    solution: "N/A",
  },
  {
    name: "N/A",
    slug: "n-a-6",
    show: "N/A",
    desc: "N/A",
    lang: ["N/A"],
    img: "N/A",
    link: "N/A",
    git: "N/A",
    problem: "N/A",
    solution: "N/A",
  },
  {
    name: "N/A",
    slug: "n-a-7",
    show: "N/A",
    desc: "N/A",
    lang: ["N/A"],
    img: "N/A",
    link: "N/A",
    git: "N/A",
    problem: "N/A",
    solution: "N/A",
  },
  {
    name: "N/A",
    slug: "n-a-8",
    show: "N/A",
    desc: "N/A",
    lang: ["N/A"],
    img: "N/A",
    link: "N/A",
    git: "N/A",
    problem: "N/A",
    solution: "N/A",
  },
];
